package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "CLIENT", catalog = "ModularisBDD")
public class Client implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer clientId;
	private DonneesPersonelle donneesPersonelle;
	private Set<Devis> devises = new HashSet<Devis>(0);

	public Client() {
	}

	public Client(DonneesPersonelle donneesPersonelle) {
		this.donneesPersonelle = donneesPersonelle;
	}

	public Client(DonneesPersonelle donneesPersonelle, Set<Devis> devises) {
		this.donneesPersonelle = donneesPersonelle;
		this.devises = devises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CLIENT_ID", unique = true, nullable = false)
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DONNEES_PERSONELLE_ID", nullable = false)
	public DonneesPersonelle getDonneesPersonelle() {
		return this.donneesPersonelle;
	}

	public void setDonneesPersonelle(DonneesPersonelle donneesPersonelle) {
		this.donneesPersonelle = donneesPersonelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Devis> getDevises() {
		return this.devises;
	}

	public void setDevises(Set<Devis> devises) {
		this.devises = devises;
	}

}
