package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Devis generated by hbm2java
 */
@Entity
@Table(name = "DEVIS", catalog = "ModularisBDD")
public class Devis implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer devisId;
	private Client client;
	private Etat etat;
	private Projet projet;
	private Utilisateur utilisateur;
	private float prixHt;
	private Date dateCreation;
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Devis() {
	}

	public Devis(Client client, Etat etat, Projet projet, Utilisateur utilisateur, float prixHt, Date dateCreation) {
		this.client = client;
		this.etat = etat;
		this.projet = projet;
		this.utilisateur = utilisateur;
		this.prixHt = prixHt;
		this.dateCreation = dateCreation;
	}

	public Devis(Client client, Etat etat, Projet projet, Utilisateur utilisateur, float prixHt, Date dateCreation,
			Set<Facture> factures) {
		this.client = client;
		this.etat = etat;
		this.projet = projet;
		this.utilisateur = utilisateur;
		this.prixHt = prixHt;
		this.dateCreation = dateCreation;
		this.factures = factures;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DEVIS_ID", unique = true, nullable = false)
	public Integer getDevisId() {
		return this.devisId;
	}

	public void setDevisId(Integer devisId) {
		this.devisId = devisId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENT_ID", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETAT_ID", nullable = false)
	public Etat getEtat() {
		return this.etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJET_ID", nullable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UTILISATEUR_ID", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "PRIX_HT", nullable = false, precision = 12, scale = 0)
	public float getPrixHt() {
		return this.prixHt;
	}

	public void setPrixHt(float prixHt) {
		this.prixHt = prixHt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREATION", nullable = false, length = 10)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "devis")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
