package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DonneesPersonelle generated by hbm2java
 */
@Entity
@Table(name = "donnees_personelle", catalog = "modularisbdd")
public class DonneesPersonelle implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer donneesPersonelleId;
	private String nom;
	private String prenom;
	private String email;
	private String adresse;
	private String ville;
	private String telephone;
	private String codePostal;
	private Set<Client> clients = new HashSet<Client>(0);
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public DonneesPersonelle() {
	}

	public DonneesPersonelle(String nom, String prenom) {
		this.nom = nom;
		this.prenom = prenom;
	}

	public DonneesPersonelle(String nom, String prenom, String email, String adresse, String telephone,
			String codePostal, String ville , Entrepot entrepot) {
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.adresse = adresse;
		this.telephone = telephone;
		this.codePostal = codePostal;
		this.ville = ville;
	}
	
	public DonneesPersonelle(String nom, String prenom, String email, String adresse, String telephone,
			String codePostal, Set<Client> clients, Set<Utilisateur> utilisateurs) {
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.adresse = adresse;
		this.telephone = telephone;
		this.codePostal = codePostal;
		this.clients = clients;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DONNEES_PERSONELLE_ID", unique = true, nullable = false)
	public Integer getDonneesPersonelleId() {
		return this.donneesPersonelleId;
	}

	public void setDonneesPersonelleId(Integer donneesPersonelleId) {
		this.donneesPersonelleId = donneesPersonelleId;
	}

	@Column(name = "NOM", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ADRESSE", length = 250)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "TELEPHONE", length = 25)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "CODE_POSTAL", length = 25)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}
	
	@Column(name = "VILLE", length = 100)
	public String getVille() {
		return ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donneesPersonelle")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donneesPersonelle")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
