package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "FACTURE", catalog = "ModularisBDD")
public class Facture implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer factureId;
	private Devis devis;
	private EtapeFacture etapeFacture;
	private Date dateModification;


	public Facture() {
	}

	public Facture(Devis devis, EtapeFacture etapeFacture) {
		this.devis = devis;
		this.etapeFacture = etapeFacture;
	}
	
	public Facture(Devis devis, EtapeFacture etapeFacture,Date dateModification) {
		this.devis = devis;
		this.etapeFacture = etapeFacture;
		this.dateModification = dateModification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FACTURE_ID", unique = true, nullable = false)
	public Integer getFactureId() {
		return this.factureId;
	}

	public void setFactureId(Integer factureId) {
		this.factureId = factureId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEVIS_ID", nullable = false)
	public Devis getDevis() {
		return this.devis;
	}

	public void setDevis(Devis devis) {
		this.devis = devis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETAPE_FACTURE_ID", nullable = false)
	public EtapeFacture getEtapeFacture() {
		return etapeFacture;
	}

	public void setEtapeFacture(EtapeFacture etapeFacture) {
		this.etapeFacture = etapeFacture;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_MODIFICATION", nullable = false,length = 10)
	public Date getDateModification() {
		return dateModification;
	}

	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}
	
	public int compareTo(Facture o) {
		return getDevis().getDateCreation().compareTo(o.getDevis().getDateCreation());
		
	}

}
