package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "modularisbdd")
public class Facture implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer factureId;
	private Devis devis;
	private EtapeFacture etapeFacture;

	

	public Facture() {
	}

	public Facture(Devis devis, EtapeFacture etapeFacture) {
		this.devis = devis;
		this.etapeFacture = etapeFacture;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FACTURE_ID", unique = true, nullable = false)
	public Integer getFactureId() {
		return this.factureId;
	}

	public void setFactureId(Integer factureId) {
		this.factureId = factureId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEVIS_ID", nullable = false)
	public Devis getDevis() {
		return this.devis;
	}

	public void setDevis(Devis devis) {
		this.devis = devis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETAPE_FACTURE_ID", nullable = false)
	public EtapeFacture getEtapeFacture() {
		return etapeFacture;
	}

	public void setEtapeFacture(EtapeFacture etapeFacture) {
		this.etapeFacture = etapeFacture;
	}
	

}
