package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FamilleComposant generated by hbm2java
 */
@Entity
@Table(name = "famille_composant", catalog = "modularisbdd")
public class FamilleComposant implements java.io.Serializable {

	private Integer familleComposantId;
	private String nom;
	private Set<Composant> composants = new HashSet<Composant>(0);

	public FamilleComposant() {
	}

	public FamilleComposant(String nom) {
		this.nom = nom;
	}

	public FamilleComposant(String nom, Set<Composant> composants) {
		this.nom = nom;
		this.composants = composants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FAMILLE_COMPOSANT_ID", unique = true, nullable = false)
	public Integer getFamilleComposantId() {
		return this.familleComposantId;
	}

	public void setFamilleComposantId(Integer familleComposantId) {
		this.familleComposantId = familleComposantId;
	}

	@Column(name = "NOM", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "familleComposant")
	public Set<Composant> getComposants() {
		return this.composants;
	}

	public void setComposants(Set<Composant> composants) {
		this.composants = composants;
	}

}
