package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name = "fournisseur", catalog = "modularisbdd")
public class Fournisseur implements java.io.Serializable {

	private Integer fournisseurId;
	private String nom;
	private String adresse;
	private String codePostal;
	private String telephone;
	private String email;
	private Set<Composant> composants = new HashSet<Composant>(0);

	public Fournisseur() {
	}

	public Fournisseur(String nom, String adresse, String codePostal) {
		this.nom = nom;
		this.adresse = adresse;
		this.codePostal = codePostal;
	}

	public Fournisseur(String nom, String adresse, String codePostal, String telephone, String email,
			Set<Composant> composants) {
		this.nom = nom;
		this.adresse = adresse;
		this.codePostal = codePostal;
		this.telephone = telephone;
		this.email = email;
		this.composants = composants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FOURNISSEUR_ID", unique = true, nullable = false)
	public Integer getFournisseurId() {
		return this.fournisseurId;
	}

	public void setFournisseurId(Integer fournisseurId) {
		this.fournisseurId = fournisseurId;
	}

	@Column(name = "NOM", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "ADRESSE", nullable = false)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "CODE_POSTAL", nullable = false, length = 25)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "TELEPHONE", length = 25)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fournisseur")
	public Set<Composant> getComposants() {
		return this.composants;
	}

	public void setComposants(Set<Composant> composants) {
		this.composants = composants;
	}

}
