package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Materiaux generated by hbm2java
 */
@Entity
@Table(name = "materiaux", catalog = "modularisbdd")
public class Materiaux implements java.io.Serializable {

	private Integer materiauxId;
	private String nom;
	private Set<Composant> composants = new HashSet<Composant>(0);

	public Materiaux() {
	}

	public Materiaux(String nom) {
		this.nom = nom;
	}

	public Materiaux(String nom, Set<Composant> composants) {
		this.nom = nom;
		this.composants = composants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MATERIAUX_ID", unique = true, nullable = false)
	public Integer getMateriauxId() {
		return this.materiauxId;
	}

	public void setMateriauxId(Integer materiauxId) {
		this.materiauxId = materiauxId;
	}

	@Column(name = "NOM", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiaux")
	public Set<Composant> getComposants() {
		return this.composants;
	}

	public void setComposants(Set<Composant> composants) {
		this.composants = composants;
	}

}
