package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModuleXComposantId generated by hbm2java
 */
@Embeddable
public class ModuleXComposantId implements java.io.Serializable {

	private int composantId;
	private int moduleId;

	public ModuleXComposantId() {
	}

	public ModuleXComposantId(int composantId, int moduleId) {
		this.composantId = composantId;
		this.moduleId = moduleId;
	}

	@Column(name = "COMPOSANT_ID", nullable = false)
	public int getComposantId() {
		return this.composantId;
	}

	public void setComposantId(int composantId) {
		this.composantId = composantId;
	}

	@Column(name = "MODULE_ID", nullable = false)
	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModuleXComposantId))
			return false;
		ModuleXComposantId castOther = (ModuleXComposantId) other;

		return (this.getComposantId() == castOther.getComposantId()) && (this.getModuleId() == castOther.getModuleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getComposantId();
		result = 37 * result + this.getModuleId();
		return result;
	}

}
