package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "modularisbdd")
public class Module implements java.io.Serializable {

	private Integer moduleId;
	private Angle angle;
	private Gamme gamme;
	private Set<Piece> pieces = new HashSet<Piece>(0);
	private String nom;
	private UniteMesure uniteMesure;
	private Integer valeurAngle;
	private Set<ModuleXComposant> moduleXComposants = new HashSet<ModuleXComposant>(0);

	public Module() {
	}

	public Module(Angle angle, Gamme gamme, String nom,UniteMesure uniteMesure) {
		this.angle = angle;
		this.gamme = gamme;
		this.nom = nom;
		this.uniteMesure = uniteMesure;
	}
	
	public Module(Angle angle, Gamme gamme, Set<Piece> pieces, String nom,UniteMesure uniteMesure) {
		this.angle = angle;
		this.gamme = gamme;
		this.pieces = pieces;
		this.nom = nom;
		this.uniteMesure = uniteMesure;
	}

	public Module(Angle angle, Gamme gamme, Set<Piece> pieces, String nom, Integer valeurAngle,UniteMesure uniteMesure,
			Set<ModuleXComposant> moduleXComposants) {
		this.angle = angle;
		this.gamme = gamme;
		this.pieces = pieces;
		this.nom = nom;
		this.valeurAngle = valeurAngle;
		this.moduleXComposants = moduleXComposants;
		this.uniteMesure = uniteMesure;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MODULE_ID", unique = true, nullable = false)
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNITE_ID", nullable = false)
	public UniteMesure getUniteMesure() {
		return this.uniteMesure;
	}

	public void setUniteMesure(UniteMesure uniteMesure) {
		this.uniteMesure = uniteMesure;
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ANGLE_ID", nullable = false)
	public Angle getAngle() {
		return this.angle;
	}

	public void setAngle(Angle angle) {
		this.angle = angle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GAMME_ID", nullable = false)
	public Gamme getGamme() {
		return this.gamme;
	}

	public void setGamme(Gamme gamme) {
		this.gamme = gamme;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "piece_x_module", catalog = "modularisbdd", joinColumns = {
			@JoinColumn(name = "MODULE_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "PIECE_ID", nullable = false, updatable = false) })
	public Set<Piece> getPieces() {
		return this.pieces;
	}

	public void setPieces(Set<Piece> pieces) {
		this.pieces = pieces;
	}

	@Column(name = "NOM", nullable = false, length = 25)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "VALEUR_ANGLE")
	public Integer getValeurAngle() {
		return this.valeurAngle;
	}

	public void setValeurAngle(Integer valeurAngle) {
		this.valeurAngle = valeurAngle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<ModuleXComposant> getModuleXComposants() {
		return this.moduleXComposants;
	}

	public void setModuleXComposants(Set<ModuleXComposant> moduleXComposants) {
		this.moduleXComposants = moduleXComposants;
	}

}
