package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Piece generated by hbm2java
 */
@Entity
@Table(name = "piece", catalog = "modularisbdd")
public class Piece implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer pieceId;
	private Plan plan;
	private String nom;
	private float surface;
	private Set<Module> modules = new HashSet<Module>(0);

	public Piece() {
	}

	public Piece(Plan plan, String nom, float surface) {
		this.plan = plan;
		this.nom = nom;
		this.surface = surface;
	}

	public Piece(Plan plan, String nom, float surface, Set<Module> modules) {
		this.plan = plan;
		this.nom = nom;
		this.surface = surface;
		this.modules = modules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PIECE_ID", unique = true, nullable = false)
	public Integer getPieceId() {
		return this.pieceId;
	}

	public void setPieceId(Integer pieceId) {
		this.pieceId = pieceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLAN_ID", nullable = false)
	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	@Column(name = "NOM", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "SURFACE", nullable = false, precision = 12, scale = 0)
	public float getSurface() {
		return this.surface;
	}

	public void setSurface(float surface) {
		this.surface = surface;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "pieces")
	public Set<Module> getModules() {
		return this.modules;
	}

	public void setModules(Set<Module> modules) {
		this.modules = modules;
	}

}
