package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plan generated by hbm2java
 */
@Entity
@Table(name = "plan", catalog = "modularisbdd")
public class Plan implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private Integer planId;
	private Projet projet;
	private String nom;
	private Set<Piece> pieces = new HashSet<Piece>(0);

	public Plan() {
	}

	public Plan(Projet projet, String nom) {
		this.projet = projet;
		this.nom = nom;
	}

	public Plan(Projet projet, String nom, Set<Piece> pieces) {
		this.projet = projet;
		this.nom = nom;
		this.pieces = pieces;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PLAN_ID", unique = true, nullable = false)
	public Integer getPlanId() {
		return this.planId;
	}

	public void setPlanId(Integer planId) {
		this.planId = planId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJET_ID", nullable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "NOM", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plan", cascade = CascadeType.ALL)
	public Set<Piece> getPieces() {
		return this.pieces;
	}

	public void setPieces(Set<Piece> pieces) {
		this.pieces = pieces;
	}

}
