package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Projet generated by hbm2java
 */
@Entity
@Table(name = "projet", catalog = "modularisbdd")
public class Projet implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer projetId;
	private Set<Catalogue> catalogue = new HashSet<Catalogue>(0);
	
	private String nom;
	
	private Boolean isClone;
	
	private Set<Devis> devises = new HashSet<Devis>(0);
	private Set<Plan> plans = new HashSet<Plan>(0);
	
	private Image image;
	
	public Projet() {
	}

	public Projet( String nom) {
		this.nom = nom;
	}
	
	public Projet( String nom,Image image) {
		this.nom = nom;
		this.image = image;
	}
	
	public Projet( String nom,Image image,Set<Plan> plans) {
		this.nom = nom;
		this.image = image;
		this.plans = plans;
	}
	
	public Projet(Set<Catalogue> catalogue, String nom) {
		this.catalogue = catalogue;
		this.nom = nom;
	}

	public Projet(Set<Catalogue> catalogue, String nom, Set<Devis> devises, Set<Plan> plans) {
		this.catalogue = catalogue;
		this.nom = nom;
		this.devises = devises;
		this.plans = plans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PROJET_ID", unique = true, nullable = false)
	public Integer getProjetId() {
		return this.projetId;
	}

	public void setProjetId(Integer projetId) {
		this.projetId = projetId;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "projets")
	public Set<Catalogue> getCatalogue() {
		return catalogue;
	}

	public void setCatalogue(Set<Catalogue> catalogue) {
		this.catalogue = catalogue;
	}

	
	@Column(name = "NOM", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet")
	public Set<Devis> getDevises() {
		return this.devises;
	}

	public void setDevises(Set<Devis> devises) {
		this.devises = devises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Plan> getPlans() {
		return this.plans;
	}

	public void setPlans(Set<Plan> plans) {
		this.plans = plans;
	}
	
	@Column(name = "IS_CLONE", nullable = true)
	public Boolean isClone() {
		return isClone;
	}

	public void setClone(Boolean isClone) {
		this.isClone = isClone;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IMAGE_ID", nullable = false)
	public Image getImage() {
		return image;
	}

	public void setImage(Image image) {
		this.image = image;
	}


}
