package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Projet generated by hbm2java
 */
@Entity
@Table(name = "projet", catalog = "modularisbdd")
public class Projet implements java.io.Serializable {

	private Integer projetId;
	private Catalogue catalogue;
	private String nom;
	private Set<Devis> devises = new HashSet<Devis>(0);
	private Set<Plan> plans = new HashSet<Plan>(0);

	public Projet() {
	}

	public Projet(Catalogue catalogue, String nom) {
		this.catalogue = catalogue;
		this.nom = nom;
	}

	public Projet(Catalogue catalogue, String nom, Set<Devis> devises, Set<Plan> plans) {
		this.catalogue = catalogue;
		this.nom = nom;
		this.devises = devises;
		this.plans = plans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PROJET_ID", unique = true, nullable = false)
	public Integer getProjetId() {
		return this.projetId;
	}

	public void setProjetId(Integer projetId) {
		this.projetId = projetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATALOGUE_ID", nullable = false)
	public Catalogue getCatalogue() {
		return this.catalogue;
	}

	public void setCatalogue(Catalogue catalogue) {
		this.catalogue = catalogue;
	}

	@Column(name = "NOM", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet")
	public Set<Devis> getDevises() {
		return this.devises;
	}

	public void setDevises(Set<Devis> devises) {
		this.devises = devises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet")
	public Set<Plan> getPlans() {
		return this.plans;
	}

	public void setPlans(Set<Plan> plans) {
		this.plans = plans;
	}

}
