package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", catalog = "modularisbdd")
public class Stock implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer stockId;
	private Entrepot entrepot;
	private int quantite;
	private Composant composant;

	public Stock() {
	}

	public Stock(Entrepot entrepot, int quantite) {
		this.entrepot = entrepot;
		this.quantite = quantite;
	}

	public Stock(Entrepot entrepot, int quantite, Composant composant) {
		this.entrepot = entrepot;
		this.quantite = quantite;
		this.composant = composant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "STOCK_ID", unique = true, nullable = false)
	public Integer getStockId() {
		return this.stockId;
	}

	public void setStockId(Integer stockId) {
		this.stockId = stockId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENTREPOT_ID", nullable = false)
	public Entrepot getEntrepot() {
		return this.entrepot;
	}

	public void setEntrepot(Entrepot entrepot) {
		this.entrepot = entrepot;
	}

	@Column(name = "QUANTITE", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPOSANT", nullable = false)
	public Composant getComposant() {
		return composant;
	}

	public void setComposant(Composant composant) {
		this.composant = composant;
	}


}
