package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", catalog = "modularisbdd")
public class Stock implements java.io.Serializable {

	private Integer stockId;
	private Entrepot entrepot;
	private int quantite;
	private Set<Composant> composants = new HashSet<Composant>(0);

	public Stock() {
	}

	public Stock(Entrepot entrepot, int quantite) {
		this.entrepot = entrepot;
		this.quantite = quantite;
	}

	public Stock(Entrepot entrepot, int quantite, Set<Composant> composants) {
		this.entrepot = entrepot;
		this.quantite = quantite;
		this.composants = composants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "STOCK_ID", unique = true, nullable = false)
	public Integer getStockId() {
		return this.stockId;
	}

	public void setStockId(Integer stockId) {
		this.stockId = stockId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENTREPOT_ID", nullable = false)
	public Entrepot getEntrepot() {
		return this.entrepot;
	}

	public void setEntrepot(Entrepot entrepot) {
		this.entrepot = entrepot;
	}

	@Column(name = "QUANTITE", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "stocks")
	public Set<Composant> getComposants() {
		return this.composants;
	}

	public void setComposants(Set<Composant> composants) {
		this.composants = composants;
	}

}
