package com.ril.model;
// Generated 9 janv. 2019 13:15:45 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UniteMesure generated by hbm2java
 */
@Entity
@Table(name = "unite_mesure", catalog = "modularisbdd")
public class UniteMesure implements java.io.Serializable {

	private Integer uniteId;
	private String nomUnite;
	private Set<Module> module = new HashSet<Module>(0);

	public UniteMesure() {
	}

	public UniteMesure(String nomUnite) {
		this.nomUnite = nomUnite;
	}

	public UniteMesure(String nomUnite, Set<Module> module) {
		this.nomUnite = nomUnite;
		this.module = module;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UNITE_MESURE_ID", unique = true, nullable = false)
	public Integer getUniteId() {
		return this.uniteId;
	}

	public void setUniteId(Integer uniteId) {
		this.uniteId = uniteId;
	}

	@Column(name = "NOM", nullable = false, length = 25)
	public String getNomUnite() {
		return this.nomUnite;
	}

	public void setNomUnite(String nomUnite) {
		this.nomUnite = nomUnite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "uniteMesure")
	public Set<Module> getModules() {
		return this.module;
	}

	public void setModules(Set<Module> module) {
		this.module = module;
	}

}
