package com.ril.model;
// Generated 9 janv. 2019 10:36:15 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR", catalog = "ModularisBDD")
public class Utilisateur implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer utilisateurId;
	private DonneesPersonelle donneesPersonelle;
	private Metier metier;
	private String login;
	private String password;
	private Entrepot entrepot;
	private Set<Devis> devises = new HashSet<Devis>(0);

	public Utilisateur() {
	}

	public Utilisateur(DonneesPersonelle donneesPersonelle, Metier metier, String login, String password , Entrepot entrepot) {
		this.donneesPersonelle = donneesPersonelle;
		this.metier = metier;
		this.login = login;
		this.password = password;
		this.entrepot = entrepot;
	}

	public Utilisateur(DonneesPersonelle donneesPersonelle, Metier metier, String login, String password,
			Set<Devis> devises) {
		this.donneesPersonelle = donneesPersonelle;
		this.metier = metier;
		this.login = login;
		this.password = password;
		this.devises = devises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UTILISATEUR_ID", unique = true, nullable = false)
	public Integer getUtilisateurId() {
		return this.utilisateurId;
	}

	public void setUtilisateurId(Integer utilisateurId) {
		this.utilisateurId = utilisateurId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DONNEES_PERSONELLE_ID", nullable = false)
	public DonneesPersonelle getDonneesPersonelle() {
		return this.donneesPersonelle;
	}

	public void setDonneesPersonelle(DonneesPersonelle donneesPersonelle) {
		this.donneesPersonelle = donneesPersonelle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "METIER_ID", nullable = false)
	public Metier getMetier() {
		return this.metier;
	}

	public void setMetier(Metier metier) {
		this.metier = metier;
	}

	@Column(name = "LOGIN", nullable = false, length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Devis> getDevises() {
		return this.devises;
	}

	public void setDevises(Set<Devis> devises) {
		this.devises = devises;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENTREPOT_ID", nullable = false)
	public Entrepot getEntrepot() {
		return entrepot;
	}

	public void setEntrepot(Entrepot entrepot) {
		this.entrepot = entrepot;
	}

}
